=== LucaasDelgadoo/1-DAM/Lenguaje de marcas/3 EV/SCHEMAS/Ejercicios XSD/xsd y dtd/ejercicio1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="libro">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="capitulo" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="titulo" type="xs:string"/>
                            <xs:element name="subcapitulo" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="titulo" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== LucaasDelgadoo/1-DAM/Lenguaje de marcas/3 EV/SCHEMAS/Ejercicios XSD/xml/ejercicio1_xsd.xml
<?xml version="1.0" encoding="UTF-8"?> 
<libro xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ejercicio1.xsd"> 
    <capitulo> 
        <titulo>Introduccion</titulo> 
    </capitulo> 
    <capitulo> 
        <titulo>Historia</titulo> 
        <subcapitulo> 
            <titulo>Parte 1</titulo> 
        </subcapitulo> 
        <subcapitulo> 
            <titulo>Parte 2</titulo> 
        </subcapitulo> 
    </capitulo> 
    <capitulo> 
        <titulo>Index</titulo> 
    </capitulo> 
</libro>
