=== LucaasDelgadoo/1-DAM/Lenguaje de marcas/3 EV/SCHEMAS/Ejercicios XSD/xsd y dtd/ejercicio6.dtd
<!ELEMENT Recetario (Autor, Receta+, Fecha)>
<!ELEMENT Autor (#PCDATA)>
<!ELEMENT Receta (Nombre, Origen?, Ingredientes, Elaboracion, Referencia?)>
<!ATTLIST Receta 
          dificultad CDATA #REQUIRED
          coste CDATA #REQUIRED
          NivelCalorias CDATA #REQUIRED
          tipo CDATA #IMPLIED>
<!ELEMENT Nombre (#PCDATA)>
<!ELEMENT Origen (#PCDATA)>
<!ELEMENT Ingredientes (Ingrediente+)>
<!ELEMENT Ingrediente (NombreI, Cantidad)>
<!ATTLIST Ingrediente 
          medida CDATA #IMPLIED>
<!ELEMENT NombreI (#PCDATA)>
<!ELEMENT Cantidad (#PCDATA)>
<!ELEMENT Elaboracion (Paso+)>
<!ELEMENT Paso (#PCDATA)>
<!ELEMENT Referencia (#PCDATA)>
<!ELEMENT Fecha (#PCDATA)>

=== LucaasDelgadoo/1-DAM/Lenguaje de marcas/3 EV/SCHEMAS/Ejercicios XSD/xml/ejercicio6_xsd.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE Recetario SYSTEM "ejercicio6.dtd">
<Recetario xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="ejercicio6.xsd">
	<Autor>Karlos Argui�ano</Autor>
	<Receta dificultad="f�cil" coste="Bajo" NivelCalorias="bajo">
		<Nombre>Crema de puerros</Nombre>
		<Origen>Cocina espa�ola</Origen>
		<Ingredientes>
			<Ingrediente medida="gramos">
				<NombreI>puerros</NombreI>
				<Cantidad>2500</Cantidad>
			</Ingrediente>
			<Ingrediente medida="piezas">
				<NombreI>patatas</NombreI>
				<Cantidad>3</Cantidad>
			</Ingrediente>
			<Ingrediente medida="cucharadas">
				<NombreI>arroz</NombreI>
				<Cantidad>3</Cantidad>
			</Ingrediente>
			<Ingrediente medida="gramos">
				<NombreI>pechuga de pollo</NombreI>
				<Cantidad>250</Cantidad>
			</Ingrediente>
			<Ingrediente medida="cucharadas">
				<NombreI>mantequilla</NombreI>
				<Cantidad>1</Cantidad>
			</Ingrediente>
			<Ingrediente medida="gramos">
				<NombreI>nata l�quida</NombreI>
				<Cantidad>5</Cantidad>
			</Ingrediente>
			<Ingrediente>
				<NombreI>pimienta molida</NombreI>
				<Cantidad>
            </Cantidad>
			</Ingrediente>
			<Ingrediente>
				<NombreI>nuez moscada</NombreI>
				<Cantidad>
            </Cantidad>
			</Ingrediente>
		</Ingredientes>
		<Elaboracion>
			<Paso>Hervir 1/2 hora en la olla los puerros, las patatas, el arroz y el pollo.</Paso>
			<Paso>A�adir una cucharada de mantequilla, pasarlo por la batidora y colarlo.</Paso>
			<Paso>A�adir pimienta molida y nuez moscada rallada al gusto.</Paso>
			<Paso>Mezclar nata l�quida 1 caja, dejando un poco para adornar las tazas al servir junto con un poco de la pechuga muy menudita.</Paso>
		</Elaboracion>
	</Receta>
	<Receta tipo="Postre" dificultad="f�cil" coste="Bajo" NivelCalorias="alto">
		<Nombre>Blinis</Nombre>
		<Origen>Cocina rusa</Origen>
		<Ingredientes>
			<Ingrediente medida="vasos">
				<NombreI>harina</NombreI>
				<Cantidad>1,5</Cantidad>
			</Ingrediente>
			<Ingrediente medida="cucharadas">
				<NombreI>leche entera</NombreI>
				<Cantidad>4</Cantidad>
			</Ingrediente>
			<Ingrediente medida="cucharadas">
				<NombreI>levadura</NombreI>
				<Cantidad>4</Cantidad>
			</Ingrediente>
			<Ingrediente>
				<NombreI>huevos</NombreI>
				<Cantidad>3</Cantidad>
			</Ingrediente>
			<Ingrediente medida="cucharadas de caf�">
				<NombreI>sal</NombreI>
				<Cantidad>1</Cantidad>
			</Ingrediente>
			<Ingrediente>
				<NombreI>mantequilla derretida</NombreI>
				<Cantidad>5</Cantidad>
			</Ingrediente>
		</Ingredientes>
		<Referencia><![CDATA[www.platodeldia.com/recetas/?id=8805]]></Referencia>
	</Receta>
	<Receta tipo="verdura" dificultad="f�cil" coste="Bajo" NivelCalorias="medio">
		<Nombre>Berenjenas al Im�n</Nombre>
		<Origen>Cocina bizantina</Origen>
		<Ingredientes>
			<Ingrediente medida="piezas">
				<NombreI>berenjenas peque�as</NombreI>
				<Cantidad>4</Cantidad>
			</Ingrediente>
			<Ingrediente>
				<NombreI>aceite oliva</NombreI>
				<Cantidad>
            </Cantidad>
			</Ingrediente>
			<Ingrediente medida="pieza">
				<NombreI>cebollas</NombreI>
				<Cantidad>1</Cantidad>
			</Ingrediente>
			<Ingrediente medida="piezas">
				<NombreI>dientes de ajo</NombreI>
				<Cantidad>2</Cantidad>
			</Ingrediente>
			<Ingrediente medida="piezas">
				<NombreI>tomates</NombreI>
				<Cantidad>2</Cantidad>
			</Ingrediente>
			<Ingrediente>
				<NombreI>sal</NombreI>
				<Cantidad>
            </Cantidad>
			</Ingrediente>
			<Ingrediente>
				<NombreI>pimienta</NombreI>
				<Cantidad>
            </Cantidad>
			</Ingrediente>
			<Ingrediente>
				<NombreI>tomillo</NombreI>
				<Cantidad>
            </Cantidad>
			</Ingrediente>
			<Ingrediente>
				<NombreI>perejil</NombreI>
				<Cantidad>
            </Cantidad>
			</Ingrediente>
			<Ingrediente medida="cucharada de caf�">
				<NombreI>mantequilla</NombreI>
				<Cantidad>1</Cantidad>
			</Ingrediente>
			<Ingrediente>
				<NombreI>agua</NombreI>
				<Cantidad>
            </Cantidad>
			</Ingrediente>
		</Ingredientes>
		<Elaboracion>
			<Paso>Se lavan las berenjenas y se pelan en bandas longitudinales.</Paso>
			<Paso>Las peladuras, de un cent�metro de ancho, deben alternarse con la pulpa, tambi�n de un centr�metro de grosor.</Paso>
			<Paso>Hacemos en las berenjenas una incisi�n lateral a trav�s de la cual se extraer, con ayuda de una cucharilla, un cuarto de su pulpa.</Paso>
			<Paso>Se doran las berenjenas en aceite caliente durente 3 minutos y se retiran.</Paso>
			<Paso>En el mismo aceite se rehogan la cebollas y los ajos picados.</Paso>
			<Paso>Se a�aden los tomates, pelados y troceados, la pulpa de las berenjenas, el perejil y tomillo.</Paso>
			<Paso>Salpimentar y cocer durante 15 minutos. Se rellenan las berenjenas con esta mezcla y se disponen en una fuente, con el lado relleno hacia arriba y cubiertas con un poco de mantequilla y agua.</Paso>
			<Paso>Se hornea durante 20 minutos y listo para servir.</Paso>
		</Elaboracion>
	</Receta>
	<Receta tipo="entrante" dificultad="f�cil" coste="Bajo" NivelCalorias="medio">
		<Nombre>Crepes de Esp�rragos</Nombre>
		<Origen>Cocina espa�ola</Origen>
		<Ingredientes>
			<Ingrediente medida="manojo">
				<NombreI>esp�rragos trigueros</NombreI>
				<Cantidad>1</Cantidad>
			</Ingrediente>
			<Ingrediente medida="litro">
				<NombreI>leche</NombreI>
				<Cantidad>1/4</Cantidad>
			</Ingrediente>
			<Ingrediente medida="cucharadas soperas">
				<NombreI>mantequilla</NombreI>
				<Cantidad>3</Cantidad>
			</Ingrediente>
			<Ingrediente medida="cucharadas">
				<NombreI>harina</NombreI>
				<Cantidad>6</Cantidad>
			</Ingrediente>
			<Ingrediente>
				<NombreI>huevos</NombreI>
				<Cantidad>3</Cantidad>
			</Ingrediente>
			<Ingrediente medida="cucharada de caf�">
				<NombreI>co�ac</NombreI>
				<Cantidad>1</Cantidad>
			</Ingrediente>
			<Ingrediente>
				<NombreI>salsa bechamel</NombreI>
				<Cantidad>
            </Cantidad>
			</Ingrediente>
			<Ingrediente>
				<NombreI>sal</NombreI>
				<Cantidad>
            </Cantidad>
			</Ingrediente>
		</Ingredientes>
		<Elaboracion>
			<Paso>Mezclar la leche con 2 cucharadas soperas de mantequilla derretida, la harina, los huevos y el co�ac.</Paso>
			<Paso>Sazonar con sal y dejar reposar durante 30 min.</Paso>
			<Paso>Cortar la parte tierna de los esp�rragos en trozos peque�os y rehogar en el resto de mantequilla durante 10 min.</Paso>
			<Paso>Mezclar con la masa de las crepes.</Paso>
			<Paso>Derretir un poco de mantequilla en una sart�n peque�a, echar 2 cucharadas de la masa de crepes y cuando est� cocida darle la vuelta para que quede dorada por ambos lados.</Paso>
			<Paso>Preparar el resto de las crepes del mismo modo, enrollarlas y servirlas con salsa besamel.</Paso>
		</Elaboracion>
	</Receta>
	<Receta>
		<Nombre>Crepes suzettes</Nombre>
		<Origen>
      </Origen>
		<Ingredientes>
			<Ingrediente medida="mitades de vaso">
				<NombreI>harina</NombreI>
				<Cantidad>3</Cantidad>
			</Ingrediente>
			<Ingrediente>
				<NombreI>huevos</NombreI>
				<Cantidad>2</Cantidad>
			</Ingrediente>
			<Ingrediente medida="mitades de cucharada sopera">
				<NombreI>leche</NombreI>
				<Cantidad>5</Cantidad>
			</Ingrediente>
			<Ingrediente medida="cucharadas soperas">
				<NombreI>aceite oliva</NombreI>
				<Cantidad>2</Cantidad>
			</Ingrediente>
			<Ingrediente>
				<NombreI>sal</NombreI>
				<Cantidad>
            </Cantidad>
			</Ingrediente>
			<Ingrediente>
				<NombreI>pimienta molida</NombreI>
				<Cantidad>
            </Cantidad>
			</Ingrediente>
			<Ingrediente medida="cucharadas soperas">
				<NombreI>mantequilla</NombreI>
				<Cantidad>8</Cantidad>
			</Ingrediente>
			<Ingrediente medida="naranjas">
				<NombreI>zumo de naranja</NombreI>
				<Cantidad>2</Cantidad>
			</Ingrediente>
			<Ingrediente medida="cucharadas soperas">
				<NombreI>az�car</NombreI>
				<Cantidad>6</Cantidad>
			</Ingrediente>
			<Ingrediente medida="vaso">
				<NombreI>licor de Grand Marnier</NombreI>
				<Cantidad>1/3</Cantidad>
			</Ingrediente>
		</Ingredientes>
		<Elaboracion>
			<Paso>Batir la harina para crepes, los huevos, el aceite y la sal.</Paso>
			<Paso>A�adir la leche y 1/2 cucharada sopera de agua sin dejar de batir.</Paso>
			<Paso>Cuando la masa est� homeg�nea, dejar de batir y echar en un recipiente.</Paso>
			<Paso>Dejar que repose durante 1 h.</Paso>
			<Paso>Repartir la masa en medidas de 1 cazo y freir en dos sartenes al mismo tiempo.</Paso>
			<Paso>A medida que se vayan haciendo, reservar calientes, preferiblemente al ba�o Mar�a.</Paso>
			<Paso>Tapar con papel de aluminio.</Paso>
			<Paso>Para el sirope, derretir la mantequilla en un cazo con el az�car, el zumo de naranja y unas cuantas ralladuras de naranja y la mitad del Grand Marnier.</Paso>
			<Paso>Calentar la otra mitad en otro cazo.</Paso>
			<Paso>Cuando se vaya a servir, calentar el sirope y el Grand Marnier.</Paso>
			<Paso>Echar las crepes dobladas en una sart�n.</Paso>
			<Paso>Regar con el sirope hirviendo y el Grand Marnier.</Paso>
			<Paso>Flambear.</Paso>
		</Elaboracion>
	</Receta>
	<Fecha>26 de Abril de 2006</Fecha>
</Recetario>
