=== LucaasDelgadoo/1-DAM/Lenguaje de marcas/3 EV/SCHEMAS/Ejercicios XSD/xsd y dtd/ejercicio2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <xsd:element name="empleados">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="empleado" maxOccurs="unbounded">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="nombre" type="xsd:string"/>
                            <xsd:element name="apellidos" type="xsd:string"/>
                            <xsd:element name="puesto">
                                <xsd:complexType>
                                    <xsd:simpleContent>
                                        <xsd:extension base="xsd:string">
                                            <xsd:attribute name="categoria" type="xsd:string" use="required"/>
                                        </xsd:extension>
                                    </xsd:simpleContent>
                                </xsd:complexType>
                            </xsd:element>
                            <xsd:element name="permanencia">
                                <xsd:complexType>
                                    <xsd:attribute name="tiempo" type="xsd:integer" use="required"/>
                                </xsd:complexType>
                            </xsd:element>
                            <xsd:element name="proyectos" minOccurs="0">
                                <xsd:complexType>
                                    <xsd:sequence>
                                        <xsd:element name="proyecto" maxOccurs="unbounded">
                                            <xsd:complexType>
                                                <xsd:simpleContent>
                                                    <xsd:extension base="xsd:string">
                                                        <xsd:attribute name="tipo" type="xsd:string" use="required"/>
                                                    </xsd:extension>
                                                </xsd:simpleContent>
                                            </xsd:complexType>
                                        </xsd:element>
                                    </xsd:sequence>
                                </xsd:complexType>
                            </xsd:element>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

</xsd:schema>

=== LucaasDelgadoo/1-DAM/Lenguaje de marcas/3 EV/SCHEMAS/Ejercicios XSD/xml/ejercicio2_xsd.xml
<?xml version="1.0" encoding="UTF-8"?>
<empleados xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="ejercicio2.xsd">
    <empleado>
        <nombre>Alejandro</nombre>
        <apellidos>Mart√≠n Ledesma</apellidos>
        <puesto categoria="senior">programador</puesto>
        <permanencia tiempo="10" />
        <proyectos>
            <proyecto tipo="curso">Curso XML</proyecto>
            <proyecto tipo="web">GPM</proyecto>
        </proyectos>
    </empleado>
    <empleado>
        <nombre>Marta</nombre>
        <apellidos>Marcos Lasa</apellidos>
        <puesto categoria="auxiliar">programador</puesto>
        <permanencia tiempo="0" />
    </empleado>
</empleados>
