<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE favoritos [
    <!ELEMENT favoritos (marcador*)> <!--La
    raíz debe permitir múltiples marcadores. Corrección: Cambiar marcador por marcador*. -->
    <!ELEMENT marcador (nombre, uri)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT uri (#PCDATA)>
]>
<favoritos> <!--Cambiar
    <marcadores> por <favoritos> para que coincida con la DTD. -->
    <marcador>
        <nombre>W3C</nombre>
        <uri>http://www.w3.org/</uri>
    </marcador>
    <marcador>
        <nombre>Web Hypertext Application Technology Working Group (WHATWG)</nombre>
        <uri>http://www.whatwg.org/</uri>
    </marcador>
</favoritos>

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE efemerides [
    <!ELEMENT efemerides (efemeride*)> <!--Debe
    permitir múltiples efemérides. Corrección: Cambiar efemeride por efemeride*. -->
    <!ELEMENT efemeride (fecha, hecho)>
    <!ELEMENT fecha (#PCDATA)>
    <!ELEMENT hecho (#PCDATA)>
]>
<efemerides>
    <efemeride>
        <fecha>20 de julio de 1969</fecha>
        <hecho>Llegada del hombre a la Luna</hecho>
    </efemeride>
    <efemeride>
        <fecha>12 de octubre de 1492</fecha>
        <hecho>Llegada de Colón a América</hecho>
    </efemeride>
    <efemeride>
        <fecha>6 de abril de 1909</fecha>
        <hecho>Llegada de Robert Peary al Polo Norte</hecho>
    </efemeride>
</efemerides>

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE aeropuertos [
    <!ELEMENT aeropuertos (aeropuerto*)>
    <!ELEMENT aeropuerto (nombre, cerrado?)> <!--El
    elemento "cerrado" no es opcional en la DTD. Corrección: Hacer "cerrado" opcional usando "?". -->
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT cerrado (#PCDATA)>
]>
<aeropuertos>
    <aeropuerto>
        <nombre>Berlín Schönefeld (SFX)</nombre>
        <cerrado>No</cerrado> <!--Añadido
        elemento "cerrado" para cumplir la DTD. -->
    </aeropuerto>
    <aeropuerto>
        <nombre>Berlín Tempelhof (THF)</nombre>
        <cerrado>Sí</cerrado> <!--Añadido
        elemento "cerrado". -->
    </aeropuerto>
</aeropuertos>

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE vuelos [
    <!ELEMENT vuelos (vuelo*)>
    <!ELEMENT vuelo (origen, destino)> <!--Destino
    no estaba definido en la DTD. Corrección: Añadir definición de destino. -->
    <!ELEMENT origen (#PCDATA)>
    <!ELEMENT destino (#PCDATA)> <!--Añadida
    definición del elemento destino. -->
]>
<vuelos>
    <vuelo>
        <origen>Valencia (VLC)</origen>
        <destino>Londres Heathrow (LHR)</destino>
    </vuelo>
    <vuelo>
        <origen>París Charles de Gaulle (CDG)</origen> <!--Consistencia
        en los acentos. -->
        <destino>Berlín Schönefeld (SFX)</destino>
    </vuelo>
</vuelos>

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE reyesEspa ñoles [
 <!ELEMENT reyesEspañoles (rey | reina)*>
 <!ELEMENT rey (nombre, padre, madre)>
 <!ELEMENT reina (nombre, padre, madre)> <!--Reina no estaba definida. Corrección: Añadir definición para reina. -->
 <!ELEMENT nombre (#PCDATA)>
 <!ELEMENT padre (#PCDATA)>
 <!ELEMENT madre (#PCDATA)>
]>
<reyesEspañoles>
    <rey>
        <nombre>Felipe III</nombre>
        <padre>Felipe II</padre>
        <madre>Ana de Austria</madre>
    </rey>
    <reina>
        <nombre>Juana la Loca</nombre>
        <padre>Fernando el Católico</padre>
        <madre>Isabel la Católica</madre>
    </reina>
    <rey>
        <nombre>Carlos I</nombre>
        <padre>Felipe el Hermoso</padre>
        <madre>Juana la Loca</madre>
    </rey>
</reyesEspañoles>

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE paises [
    <!ELEMENT paises (pais*)> <!--No
    se definió el contenedor "paises". Corrección: Añadir elemento contenedor "paises". -->
    <!ELEMENT pais (nombre, unionEuropea?, otan?)> <!--UnionEuropea
    y otan deben ser opcionales usando "?". -->
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT unionEuropea (#PCDATA)> <!--Cambiado
    EMPTY a (#PCDATA). -->
    <!ELEMENT otan (#PCDATA)>
]>
<paises>
    <pais>
        <nombre>España</nombre>
        <unionEuropea>Sí</unionEuropea>
        <otan>Sí</otan>
    </pais>
    <pais>
        <nombre>Noruega</nombre>
        <otan>Sí</otan>
    </pais>
    <pais>
        <nombre>Austria</nombre>
        <unionEuropea>Sí</unionEuropea>
    </pais>
</paises>

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE colores [
    <!ELEMENT colores (color*)>
    <!ELEMENT color (nombreSvg, codigo)> <!--Se
    debía definir un contenedor "codigo". Corrección: Añadir "codigo" como elemento secundario. -->
    <!ELEMENT nombreSvg (#PCDATA)>
    <!ELEMENT codigo (rgb?, cmyk?)> <!--Código
    puede tener RGB o CMYK opcionales. -->
    <!ELEMENT rgb (#PCDATA)>
    <!ELEMENT cmyk (#PCDATA)>
]>
<colores>
    <color>
        <nombreSvg>Purple</nombreSvg>
        <codigo>
            <rgb>#800080</rgb>
        </codigo>
    </color>
    <color>
        <nombreSvg>Purple</nombreSvg>
        <codigo>
            <cmyk>#00FF007F</cmyk>
        </codigo>
    </color>
</colores>

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE contabilidad [
    <!ELEMENT contabilidad (apunte*)> <!--El
    elemento "apunte" no estaba definido. Corrección: Cambiar ingreso/gasto por apunte. -->
    <!ELEMENT apunte (ingreso?, gasto?, fecha, cantidad, concepto)>
    <!ELEMENT ingreso EMPTY>
    <!ELEMENT gasto EMPTY>
    <!ELEMENT fecha (#PCDATA)>
    <!ELEMENT cantidad (#PCDATA)>
    <!ELEMENT concepto (#PCDATA)>
]>
<contabilidad>
    <apunte>
        <ingreso />
        <fecha>24 de febrero</fecha>
        <cantidad>1800,00 €</cantidad>
        <concepto>Salario</concepto>
    </apunte>
    <apunte>
        <gasto />
        <fecha>28 de febrero</fecha>
        <cantidad>74,25 €</cantidad>
        <concepto>Recibo luz</concepto>
    </apunte>
</contabilidad>

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mensajes [
    <!ELEMENT mensajes (mensaje*)> <!--Permitir
    múltiples mensajes. -->
    <!ELEMENT mensaje (de, para, hora, texto)>
    <!ELEMENT de (#PCDATA)>
    <!ELEMENT para (#PCDATA)>
    <!ELEMENT hora (#PCDATA)>
    <!ELEMENT texto (#PCDATA)>
]>
<mensajes>
    <mensaje>
        <de>Pepe (pepe@example.com)</de>
        <para>Juan (juan@example.com)</para>
        <hora>28/01/2021 17:48:23,61</hora>
        <texto>¿Hola, Juan, qué haces?</texto>
    </mensaje>
    <mensaje>
        <de>Juan (juan@example.com)</de>
        <para>Pepe (pepe@example.com)</para>
        <hora>28/01/2021 17:54:20,87</hora>
        <texto>Aquí, aprendiendo XML</texto> <!--Eliminar
        <strong> ya que no está definido en la DTD. -->
    </mensaje>
</mensajes>