<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE liga [
    <!ELEMENT liga (partido+)>
    <!ELEMENT partido (equipolocal, equipovisitante)>
    <!ELEMENT equipolocal (nombre, goles)>
    <!ELEMENT equipovisitante (nombre, goles)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT goles (#PCDATA)>
]>
<liga>
    <partido>
        <equipolocal>
            <nombre>Nottingham Presa</nombre>
            <goles>0</goles>
        </equipolocal>
        <equipovisitante>
            <nombre>Inter de Mitente</nombre>
            <goles>1</goles>
        </equipovisitante>
    </partido>
    <partido>
        <equipolocal>
            <nombre>Vodka Juniors</nombre>
            <goles>3</goles>
        </equipolocal>
        <equipovisitante>
            <nombre>Sparta da Risa</nombre>
            <goles>3</goles>
        </equipovisitante>
    </partido>
    <partido>
        <equipolocal>
            <nombre>Water de Munich</nombre>
            <goles>4</goles>
        </equipolocal>
        <equipovisitante>
            <nombre>Esteaua es del grifo</nombre>
            <goles>2</goles>
        </equipovisitante>
    </partido>
</liga>
