<!DOCTYPE numeros [
 <!ELEMENT numeros (numero)>
 <!ELEMENT numero (#PCDATA)>
]>
<numeros>
 <numero>25</numero>
</numeros>

<!DOCTYPE letras [
 <!ELEMENT letras (letra+)>
 <!ELEMENT letra (#PCDATA)>
]>
<letras>
 <letra>m</letra>
 <letra>uve doble</letra>
</letras>

<!DOCTYPE colores [
 <!ELEMENT colores (color+)>
 <!ELEMENT color (#PCDATA)>
]>
<colores>
 <color>azul marino</color>
 <color>amarillo</color>
</colores>

<!DOCTYPE flores [
 <!ELEMENT flores (flor+)>
 <!ELEMENT flor (#PCDATA)>
]>
<flores>
 <flor>Rosa</flor>
</flores>

<!DOCTYPE animales [
 <!ELEMENT animales (animal+)>
 <!ELEMENT animal (#PCDATA)>
]>
<animales>
 <animal>Caniche</animal>
 <animal>Siam√©s</animal>
</animales>

<!DOCTYPE escritores [
 <!ELEMENT escritores (escritor*)>
 <!ELEMENT escritor (nombre, nacimiento)>
 <!ELEMENT nombre (#PCDATA)>
 <!ELEMENT nacimiento (#PCDATA)>
]>
<escritores>
 <escritor>
  <nombre>Mario Vargas Llosa</nombre>
  <nacimiento>28 de marzo de 1936</nacimiento>
 </escritor>
 <escritor>
  <nombre>Milan Kundera</nombre>
  <nacimiento>1 de abril de 1929</nacimiento>
 </escritor>
</escritores>

<!DOCTYPE musicos [
 <!ELEMENT musicos (musico*)>
 <!ELEMENT musico (nombre, fechaNacimiento)>
 <!ELEMENT nombre (#PCDATA)>
 <!ELEMENT fechaNacimiento (#PCDATA)>
]>
<musicos>
 <musico>
  <nombre>Antonio Vivaldi</nombre>
  <fechaNacimiento>4 de marzo de 1678</fechaNacimiento>
 </musico>
 <musico>
  <nombre>Johann Sebastian Bach</nombre>
  <fechaNacimiento>21 de marzo de 1685</fechaNacimiento>
 </musico>
</musicos>

<!DOCTYPE agenda [
 <!ELEMENT agenda (contacto*)>
 <!ELEMENT contacto (nombre, telefonoFijo*, telefonoMovil+)>
 <!ELEMENT nombre (#PCDATA)>
 <!ELEMENT telefonoFijo (#PCDATA)>
 <!ELEMENT telefonoMovil (#PCDATA)>
]>
<agenda>
 <contacto>
  <nombre>Ayuntamiento</nombre>
  <telefonoFijo>010</telefonoFijo>
  <telefonoMovil>Desconocido</telefonoMovil>
 </contacto>
 <contacto>
  <nombre>Emergencias</nombre>
  <telefonoFijo>112</telefonoFijo>
  <telefonoMovil>Desconocido</telefonoMovil>
 </contacto>
</agenda>

<!DOCTYPE sistemaSolar [
 <!ELEMENT sistemaSolar (cuerpo*)>
 <!ELEMENT cuerpo ((planeta | satelite | asteroide)+)>
 <!ELEMENT planeta (#PCDATA)>
 <!ELEMENT satelite (#PCDATA)>
 <!ELEMENT asteroide (#PCDATA)>
]>
<sistemaSolar>
 <cuerpo>
  <planeta>Tierra</planeta>
  <satelite>Luna</satelite>
  <asteroide>Ceres</asteroide>
 </cuerpo>
</sistemaSolar>
